# Generated by Django 2.2 on 2023-04-03 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('season', models.IntegerField()),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField()),
                ('team1', models.CharField(max_length=255)),
                ('team2', models.CharField(max_length=255)),
                ('toss_winner', models.CharField(max_length=255)),
                ('toss_decision', models.CharField(max_length=255)),
                ('result', models.CharField(max_length=255)),
                ('dl_applied', models.BooleanField()),
                ('winner', models.CharField(blank=True, max_length=255, null=True)),
                ('win_by_runs', models.IntegerField(blank=True, null=True)),
                ('win_by_wickets', models.IntegerField(blank=True, null=True)),
                ('player_of_match', models.CharField(blank=True, max_length=255, null=True)),
                ('venue', models.CharField(max_length=255)),
                ('umpire1', models.CharField(blank=True, max_length=255, null=True)),
                ('umpire2', models.CharField(blank=True, max_length=255, null=True)),
                ('umpire3', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'matches',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inning', models.IntegerField()),
                ('batting_team', models.CharField(max_length=255)),
                ('bowling_team', models.CharField(max_length=255)),
                ('over', models.IntegerField()),
                ('ball', models.IntegerField()),
                ('batsman', models.CharField(max_length=255)),
                ('non_striker', models.CharField(max_length=255)),
                ('bowler', models.CharField(max_length=255)),
                ('is_super_over', models.BooleanField()),
                ('wide_runs', models.IntegerField()),
                ('bye_runs', models.IntegerField()),
                ('legbye_runs', models.IntegerField()),
                ('noball_runs', models.IntegerField()),
                ('penalty_runs', models.IntegerField()),
                ('batsman_runs', models.IntegerField()),
                ('extra_runs', models.IntegerField()),
                ('total_runs', models.IntegerField()),
                ('player_dismissed', models.CharField(blank=True, max_length=255, null=True)),
                ('dismissal_kind', models.CharField(blank=True, max_length=255, null=True)),
                ('fielder', models.CharField(blank=True, max_length=255, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipl_data_analysis.Match')),
            ],
            options={
                'verbose_name_plural': 'deliveries',
            },
        ),
    ]
